services:
  frank-sandbox-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    volumes:
      - ./app.py:/app/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s