# 自定义项目名称，影响镜像命名
name: frank-sandbox

services:
  # Python FastAPI 沙盒服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frank-sandbox
    ports:
      - "8005:8005"  # API 服务端口
    environment:
      - PYTHONPATH=/app
      - PYTHON_ENV=production
    volumes:
      - ./app.py:/app/app.py
    restart: unless-stopped
    networks:
      - sandbox-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  sandbox-network:
    driver: bridge

volumes:
  sandbox_data:
    driver: local
      