# 自定义项目名称，影响镜像命名
name: sandbox-python

services:
  # Python FastAPI 沙盒服务
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sandbox-python
    ports:
      - "8005:8005"  # API 服务端口
    environment:
      - PYTHONPATH=/app
      - PYTHON_ENV=production
    volumes:
      - ../backend/api/main.py:/app/main.py
    restart: unless-stopped
    networks:
      - sandbox-python-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  sandbox-python-network:
    driver: bridge

volumes:
  sandbox-python-data:
    driver: local